name: ci
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Formatting
        run: |
          go fmt ./...
          go vet ./...
          git diff --exit-code
      - name: Unit tests
        run: |
          go test -short ./...
          SCRIBBLE_TEST_JSON=1 go test -short ./...
      - name: Test race conditions
        run: |
          go test -race -short ./...
          SCRIBBLE_TEST_JSON=1 go test -short ./...
      - name: Coverage
        run: |
          go test -covermode=count -coverprofile=coverage.cov ./...
          go tool cover -html=coverage.cov -o=coverage.html
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Coverage
          path: coverage.html
