name: ci
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Formatting
        run: |
          go fmt ./...
          go vet ./...
          git diff --exit-code
      - name: Unit tests with GOB
        run: |
          go test -race -short -covermode atomic -coverprofile coverage_gob.cov ./...
      - name: Send GOB coverage
        if: contains(matrix.os, 'ubuntu')
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage_gob.cov
          parallel: true
      - name: Unit tests with JSON
        run: |
          go test -race -short -covermode atomic -coverprofile coverage_json.cov ./...
        env:
          SCRIBBLE_TEST_JSON: "1"
      - name: Send JSON coverage
        if: contains(matrix.os, 'ubuntu')
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage_json.cov
          parallel: true
          parallel-finished: true
